### ISSUE TITLE
报错SyntaxError: expected expression, got '<'

### ISSUE THREAD

**Issue by 15982153332** [wusp1994/qiankunTestByWu#1]
DONE  Compiled successfully in 459ms                                                                           13:28:48

  App running at:
  - Local:   http://localhost:7104/
  - Network: http://192.168.1.6:7104/

打开浏览器报错：SyntaxError: expected expression, got '<'
找不到原因在哪里

**Comment by wusp1994** [comment]
报的是路由找不到的问题，请仔细对照 子应用的webpack配置

**Comment by 15982153332** [comment]
直接clone的，没有做任何修改，试过几次了还是报错，方便发一份源码吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wu_sp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月8日(星期五) 中午1:43
收件人:&nbsp;"wusp1994/qiankunTestByWu"<qiankunTestByWu@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wusp1994/qiankunTestByWu] 报错SyntaxError: expected expression, got '<' (#1)




报的是路由找不到的问题，请仔细对照 子应用的webpack配置

**Comment by wusp1994** [comment]
这个就是源码，可以跑通的。提供下你的 node 版本

**Comment by 15982153332** [comment]
node版本：v12.13.0



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wu_sp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月8日(星期五) 中午1:50
收件人:&nbsp;"wusp1994/qiankunTestByWu"<qiankunTestByWu@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wusp1994/qiankunTestByWu] 报错SyntaxError: expected expression, got '<' (#1)




这个就是源码，可以跑通的。提供下你的 node 版本

**Comment by wusp1994** [comment]
你把项目删掉，重新clone下，我来 试试 你的node版本

**Comment by 15982153332** [comment]
好的，谢谢回复



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wu_sp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月8日(星期五) 中午1:54
收件人:&nbsp;"wusp1994/qiankunTestByWu"<qiankunTestByWu@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wusp1994/qiankunTestByWu] 报错SyntaxError: expected expression, got '<' (#1)




你把项目删掉，重新clone下，我来 试试 你的node版本

**Comment by wusp1994** [comment]
![image](https://user-images.githubusercontent.com/26253981/68453715-620e9f80-0231-11ea-805a-eeb400ff926b.png)
可以啊没有问题

**Comment by 15982153332** [comment]
我这边还是不行，能描述一下大概的步骤吗？我是这样的，步骤是不是错了呢？
1，clone项目
2，在主应用npm install
3，分别在两个子应用npm install
4，在主应用npm run start



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wu_sp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月8日(星期五) 下午2:09
收件人:&nbsp;"wusp1994/qiankunTestByWu"<qiankunTestByWu@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wusp1994/qiankunTestByWu] 报错SyntaxError: expected expression, got '<' (#1)





 可以啊没有问题

**Comment by wusp1994** [comment]
步骤是没错，你截图下你运行后的页面，是不是 clone 错分支了，master 分支

**Comment by 15982153332** [comment]
是这样的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wu_sp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月8日(星期五) 下午2:16
收件人:&nbsp;"wusp1994/qiankunTestByWu"<qiankunTestByWu@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wusp1994/qiankunTestByWu] 报错SyntaxError: expected expression, got '<' (#1)




步骤是没错，你截图下你运行后的页面，是不是 clone 错分支了，master 分支

**Comment by 15982153332** [comment]
分支没错，是master



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wu_sp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月8日(星期五) 下午2:16
收件人:&nbsp;"wusp1994/qiankunTestByWu"<qiankunTestByWu@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wusp1994/qiankunTestByWu] 报错SyntaxError: expected expression, got '<' (#1)




步骤是没错，你截图下你运行后的页面，是不是 clone 错分支了，master 分支

**Comment by wusp1994** [comment]
我邮箱发你代码吧

**Comment by 15982153332** [comment]
非常感谢！最近几天才开始研究single-spa，感谢帮助！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wu_sp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月8日(星期五) 下午2:18
收件人:&nbsp;"wusp1994/qiankunTestByWu"<qiankunTestByWu@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wusp1994/qiankunTestByWu] 报错SyntaxError: expected expression, got '<' (#1)




我邮箱发你代码吧

**Comment by wusp1994** [comment]
不对啊，你直接访问的子应用？主应用的 端口是 7099啊

**Comment by wusp1994** [comment]
![image](https://user-images.githubusercontent.com/26253981/68454359-4f956580-0233-11ea-920d-ffddfb7ea3fe.png)

**Comment by 15982153332** [comment]
对了，7099是对的，npm start过后提示的是，多谢提醒

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wu_sp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月8日(星期五) 下午2:22
收件人:&nbsp;"wusp1994/qiankunTestByWu"<qiankunTestByWu@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wusp1994/qiankunTestByWu] 报错SyntaxError: expected expression, got '<' (#1)




不对啊，你直接访问的子应用？主应用的 端口是 7099啊

**Comment by 15982153332** [comment]
QQ邮箱：190649821@qq.com




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wu_sp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月8日(星期五) 下午2:18
收件人:&nbsp;"wusp1994/qiankunTestByWu"<qiankunTestByWu@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wusp1994/qiankunTestByWu] 报错SyntaxError: expected expression, got '<' (#1)




我邮箱发你代码吧

**Comment by wusp1994** [comment]
注意端口的访问和配置，端口被占用的话，也会启动成功，会往后加，这时候 就对不上主应用的代码了

**Comment by 15982153332** [comment]
明白，谢谢提醒，如果有可能希望我也能帮帮你！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wu_sp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月8日(星期五) 下午2:38
收件人:&nbsp;"wusp1994/qiankunTestByWu"<qiankunTestByWu@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wusp1994/qiankunTestByWu] 报错SyntaxError: expected expression, got '<' (#1)




注意端口的访问和配置，端口被占用的话，也会启动成功，会往后加，这时候 就对不上主应用的代码了

**Comment by wusp1994** [comment]
嗯嗯，为这个解决方案做贡献

**Comment by 15982153332** [comment]
hash模式，build过后放到服务器，刷新会404，请问有遇到这种情况吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wu_sp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月8日(星期五) 下午2:43
收件人:&nbsp;"wusp1994/qiankunTestByWu"<qiankunTestByWu@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wusp1994/qiankunTestByWu] 报错SyntaxError: expected expression, got '<' (#1)




嗯嗯，为这个解决方案做贡献

**Comment by wusp1994** [comment]
通过了解，官方issues不建议使用hash 模式

**Comment by 15982153332** [comment]
使用history模式不会404吗，我在使用history模式的时候，多个分别子应用切换到主应用，会出现无法加载子应用的情况




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wu_sp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 下午4:57
收件人:&nbsp;"wusp1994/qiankunTestByWu"<qiankunTestByWu@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wusp1994/qiankunTestByWu] 报错SyntaxError: expected expression, got '<' (#1)




通过了解，官方issues不建议使用hash 模式

**Comment by wusp1994** [comment]
同时只能加载一个子应用，你可运行下案例试试看，目前没遇到

**Comment by 15982153332** [comment]
同时只有一个子应用，我一共有三个子应用，子应用一打开后----返回主应用，再打开子应用二----返回主应用，再点子应用三就打不开了



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wu_sp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 下午5:01
收件人:&nbsp;"wusp1994/qiankunTestByWu"<qiankunTestByWu@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wusp1994/qiankunTestByWu] 报错SyntaxError: expected expression, got '<' (#1)




同时只能加载一个子应用，你可运行下案例试试看，目前没遇到

**Comment by wusp1994** [comment]
提供下可复现仓库

**Comment by 15982153332** [comment]
下班的时候弄个仓库，404有解决方案吗，没找到办法，希望指教一下

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wu_sp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 下午5:06
收件人:&nbsp;"wusp1994/qiankunTestByWu"<qiankunTestByWu@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wusp1994/qiankunTestByWu] 报错SyntaxError: expected expression, got '<' (#1)




提供下可复现仓库

**Comment by wusp1994** [comment]
我感觉你应该去qiankun 的那个issues去搜搜看

**Comment by wusp1994** [comment]
https://github.com/umijs/qiankun/issues

**Comment by 15982153332** [comment]
还是没找到404的原因，是不是因为这个问题太低级了，我的发布环境刷新一直404



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wu_sp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 下午5:14
收件人:&nbsp;"wusp1994/qiankunTestByWu"<qiankunTestByWu@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wusp1994/qiankunTestByWu] 报错SyntaxError: expected expression, got '<' (#1)




我感觉你应该去qiankun 的那个issues去搜搜看

**Comment by wusp1994** [comment]
你跑我这个项目有404的吗？如果你是部署的时候404， 这是vue的问题，搜索  《nginx history模式解决刷新404问题》

**Comment by 15982153332** [comment]
找到原因了，是因为其中有一个应用的router里面加了*匹配404页面，把这个去掉就正常了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wu_sp"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 下午5:51
收件人:&nbsp;"wusp1994/qiankunTestByWu"<qiankunTestByWu@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wusp1994/qiankunTestByWu] 报错SyntaxError: expected expression, got '<' (#1)




你跑我这个项目有404的吗？如果你是部署的时候404， 这是vue的问题，搜索  《nginx history模式解决刷新404问题》
