### ISSUE TITLE
为什么你们都喜欢用主应用包着子应用的这种目录结构呢？

### ISSUE THREAD

**Issue by kybetter** [wusp1994/qiankunTestByWu#2]
这个哥们的也是，https://github.com/CradelLau/microfrontend-demo

看着很不舒服啊

**Comment by wusp1994** [comment]
其实目录在哪都无所谓，只要子应用启动后，主应用的端口对上，主应用通过路由都能加载到。提到跟主应用平级的其实 更好。

**Comment by wusp1994** [comment]
多谢提醒，我也感觉，平级更符合，java的微服务习惯，已更改
