### ISSUE TITLE
子项目的组织结构问题

### ISSUE THREAD

**Issue by QxQstar** [wusp1994/qiankunTestByWu#3]
如果将microfrontend-demo，sub-app1和sub-app2都作为子项目，在另一个项目（命名为基座）中注册，加载和装载这三个子应用。在基座中不写业务代码，microfrontend-demo要始终显示，sub-app1和sub-app2装载点位于microfrontend-demo中，microfrontend-demo除了有导航，还有自己的业务界面。这种形式qiankun可以实现吗？

页面结构大概是这样的
![页面结构](https://user-images.githubusercontent.com/17845091/68578745-94c4cc00-04ad-11ea-89ad-c2a17379f2d4.png)
左侧导航和顶部导航位于同一个项目（命名为microfrontend-demo），这个项目需要一直显示。
红线框部分属于另一个项目，这个项目的装载点在microfrontend-demo中

**Comment by wusp1994** [comment]
目前已支持，请更新代码查看
