### ISSUE TITLE
你好 这个应用能支持IE edge吗

### ISSUE THREAD

**Issue by kaykie** [wusp1994/qiankunTestByWu#4]
我自己跑了一下 跑不起来 不知道是否能支持IE浏览器？
这个是报错内容
![image](https://user-images.githubusercontent.com/26200899/69044597-25f8ed00-0a30-11ea-9762-6dffca20b107.png)

**Comment by wusp1994** [comment]
是否支持IE浏览器，取决于你的项目，而不取决于 qiankun 微服务整合方案

**Comment by kaykie** [comment]
> 是否支持IE浏览器，取决于你的项目，而不取决于 qiankun 微服务整合方案

你好  我是拉了仓库 啥也没改动 在chrome跑是正常的  但是放到IE上就跑不起来了 用的ie edge，你自己可以试试 在IE上跑。

**Comment by wusp1994** [comment]
关于支持IE浏览器 可以使用 @babel/polyfill https://babeljs.io/docs/en/babel-polyfill ,以及搜索引擎 vue 项目兼容 IE配置，此项目旨在解决 整合方案，不涉及，每个应用 内部详细情况

**Comment by kaykie** [comment]
> 关于支持IE浏览器 可以使用 @babel/polyfill https://babeljs.io/docs/en/babel-polyfill ,以及搜索引擎 vue 项目兼容 IE配置，此项目旨在解决 整合方案，不涉及，每个应用 内部详细情况

我其实试着加过babel，但是依然有问题，无法正常跑起来 所以想请教一下你是否有跑在IE上有Demo
