### ISSUE TITLE
build后，部署自己本地nginx，菜单栏不见了

### ISSUE THREAD

**Issue by FishLuo1992** [wusp1994/qiankunTestByWu#8]
步骤：1. 分别打包成dist， 部署到nginx，sub1开 7100， sub2开 7101端口。主应用开： 8006端口
           2. 打开页面 查看 8006端口，主页面菜单栏不显示。
           

![Uploading 1575357840(1).png…]()

**Comment by wusp1994** [comment]
图片挂掉了。部署nginx配置端口要与各个应用中的端口一致

**Comment by FishLuo1992** [comment]
server {
        listen       9428;
        server_name  localhost;
           
        location  / {
       	    root main;
            index index.html index.htm;
            try_files $uri  $uri/  /index.html;
            client_max_body_size  500m;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
	}

    server {
        listen       7100;
        server_name  localhost;
           
        location  / {
       	    root suba;
            index index.html index.htm;
            try_files $uri  $uri/  /index.html;
            client_max_body_size  500m;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
	}

    server {
        listen       7101;
        server_name  localhost;
           
        location  / {
       	    root subb;
            index index.html index.htm;
            try_files $uri  $uri/  /index.html;
            client_max_body_size  500m;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
	}
nginx配置的端口是一致的，不知道是否有问题。
node版本是 10.16.0。
菜单栏还是不对，大佬能否提供一个部署成功的例子。

**Comment by wusp1994** [comment]
server {
        listen       9000;
        server_name  localhost;

        location / {
			root   D:\WuWorkSpace\wu_project\qiankunDemo\github\qiankunTestByWu\microfrontend-demo\dist;#文件目录 	
			try_files $uri $uri/ @router; #需要指向下面的@router否则会出现vue的路由在nginx中刷新出现404
			index  index.html;#默认起始页
        }
		
		#对应上面的@router，主要原因是路由的路径资源并不是一个真实的路径，所以无法找到具体的文件
        #因此需要rewrite到index.html中，然后交给路由在处理请求资源
		location @router {
          rewrite ^.*$ /index.html last;
        }
		
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }		
		
		#所有地址反向代理到 http://127.0.0.1:8080
        location /api {
             proxy_pass http://127.0.0.1:7100/sub-app1;
             index  index.html index.htm index.jsp;
        }
		
		#location ~ /\.
        #{
        #    deny all;
        #}	
    }	

    server {
        listen       7100;
        server_name  localhost;

        add_header Access-Control-Allow-Origin *;
        
        location / {
            root D:\WuWorkSpace\wu_project\qiankunDemo\github\qiankunTestByWu\sub-app1\dist;#文件目录
            index  index.html index.htm;#默认起始页
        }
            
    }

    server {
        listen       7101;
        server_name  localhost;

        add_header Access-Control-Allow-Origin *;
        
        location / {
            root   D:\WuWorkSpace\wu_project\qiankunDemo\github\qiankunTestByWu\sub-app2\dist;#文件目录
            index  index.html index.htm;#默认起始页
        }
    }

**Comment by wusp1994** [comment]
注意配置跨域

**Comment by FishLuo1992** [comment]
菜单栏还是无法显示。

**Comment by wusp1994** [comment]
你也不说报啥错什么的

**Comment by FishLuo1992** [comment]
没报错，就是显示不了。接口登录也是正常的

**Comment by FishLuo1992** [comment]
大佬，加你QQ了，详细讨教一哈解决方法。

**Comment by wusp1994** [comment]
部署没有任何问题，我的菜单配置的有动态权限使用mockjs 模拟接口生成数据，部署时候不会使用mockJS 所以你的菜单出不来，是因为没有使用动态api获取菜单权限数据

**Comment by wusp1994** [comment]
这个与乾坤没有关系，是主应用的自己的问题，这个方案是解决乾坤的，你可以使用另外一个主应用尝试部署，验证

**Comment by FishLuo1992** [comment]
谢谢，明白了
